version: '3.2'
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./tE-backend:/var/www/html/tE-backend
      - ./translationExchange:/var/www/html/tE-backend/tRecorderApi/frontend
      - ./config/nginx:/etc/nginx/conf.d
      - ./config:/etc/ssl
      - ./config:/etc/nginx/snippets
      - ./config:/etc/nginx/snippets
      - /static:/static
    depends_on:
      - web
  web:
    build: .
    container_name: dg01
    command: bash -c "python manage.py makemigrations api && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn -c /config/config.py tRecorderApi.wsgi"
    volumes:
      - ./tE-backend:/var/www/html/tE-backend
      - ./translationExchange:/var/www/html/tE-backend/tRecorderApi/frontend
      - /static:/static
    expose:
      - "8000"
  ap:
    build: './ap'
    container_name: ap01
    network_mode: host
    privileged: true
    stop_signal: SIGTERM
    depends_on: 
      - nginx
